### ISSUE TITLE
List items are rendered inside <p> tags

### ISSUE THREAD

**Issue by leohoe** [cloveapp/community-contentful-html-renderer-elixir#1]
Both ordered and unordered lists have their individual \<li\> contents wrapped inside \<p\> tags:
![image](https://user-images.githubusercontent.com/57145602/104136378-00e2de80-5396-11eb-883c-8c6b76f5c020.png)

This creates an unwanted line break, and an offset after the list items' ::markers (such as the ones included with Phoenix's default app.css):
![image](https://user-images.githubusercontent.com/57145602/104136400-27087e80-5396-11eb-9358-dc387f5af231.png)

**Comment by sb8244** [comment]
Can you provide the JSON that goes into this result?

This renderer is a clone of the Node.js package from Contentful. I didn't want to have deviations from their implementation across languages. As far as I can tell, they expect the `<li><p>Test</p></li>` format. See https://github.com/contentful/rich-text/blob/master/packages/rich-text-html-renderer/src/__test__/index.test.ts#L178 for their test.

Some of the rendering is not what I'd expect or want, but custom renderers can be used in those cases.

**Comment by leohoe** [comment]
Ah, I see. That's a very strange decision on Contentful's part - I see they have [an open GitHub issue](https://github.com/contentful/rich-text/issues/126) related to it already.

Here's the input data:
```elixir
%{
"content" => [
	%{
	"content" => [
		%{
		"content" => [
			%{
			"data" => %{},
			"marks" => [],
			"nodeType" => "text",
			"value" => "Diese Liste"
			}
		],
		"data" => %{},
		"nodeType" => "paragraph"
		}
	],
	"data" => %{},
	"nodeType" => "list-item"
	},
	%{
	"content" => [
		%{
		"content" => [
			%{
			"data" => %{},
			"marks" => [],
			"nodeType" => "text",
			"value" => "ist nicht"
			}
		],
		"data" => %{},
		"nodeType" => "paragraph"
		}
	],
	"data" => %{},
	"nodeType" => "list-item"
	},
	%{
	"content" => [
		%{
		"content" => [
			%{
			"data" => %{},
			"marks" => [],
			"nodeType" => "text",
			"value" => "geordnet"
			}
		],
		"data" => %{},
		"nodeType" => "paragraph"
		}
	],
	"data" => %{},
	"nodeType" => "list-item"
	}
],
"data" => %{},
"nodeType" => "unordered-list"
},
```

**Comment by sb8244** [comment]
This in particular is the problem: 

```
	"content" => [
		%{
		"content" => [
			%{
			"data" => %{},
			"marks" => [],
			"nodeType" => "text",
			"value" => "Diese Liste"
			}
		],
		"data" => %{},
		"nodeType" => "paragraph"
		}
	]
```

Because the text is wrapped in a paragraph, we'd need to know the parent/children to decide to not render the paragraph tag (via a custom render fn). It would also get funky if there are other elements involved. My guess is that this might be a limitation of the format and maybe it's being sold as a consistency thing?

**Comment by stevenrabulan** [comment]
We also prefer lists rendered without paragraph tags. We don't want the "p" tags in there for SEO/styling reasons. It shouldn't be a decision _forced_ upon us.

I request that we have full flexibility in the rich text field without adding extra elements.

Current workaround: We're planning to strip the "p" and "/p" tags from "li"'s rendered by contentful via regex.

**Comment by sb8244** [comment]
Apologies, I didn't get updates for some reason (or missed it).

Unfortunately, I don't believe this is something that this library should handle. Contentful returns the content wrapped in paragraphs, and maintaining context to strip them feels like a slippery slope. I think that the regex route is good, or you can implement your own Renderer (overwriteable via opts) and replace the content there.

If you look at https://github.com/cloveapp/community-contentful-html-renderer-elixir/blob/main/lib/contentful_renderer/html/default_renderer.ex#L45, you'll see that there is no concept of tags inside of a `li`, it's just recursively processing Contentful's data structure.
